### ISSUE TITLE
Recommended version of snakemake?

### ISSUE THREAD

**Issue by Toseph** [raphael-group/Absence-Aware-Clustering#1]
AAC recommends using python2, but snakemake only works on python version >= 3.5
Is there an older version of snakemake you recommend to ensure AAC works?

**Comment by gsatas** [comment]
You are correct that snakemake runs on Python 3, and I have updated the requirements to reflect that currently both Python 3 (to run snakemake) and Python 2 (to run associated scripts in the repo) are required. 

Hope this helps!
